package com.fr.bi.tool;

import java.io.File;

/**
 * Created by Connery on 2016/1/26.
 */
public class BIGenerateBasicJavaFile {
    /**
     * 从包开始的路径
     * 例如C:/Program/A/com/fr/bi
     * 其中com/fr/bi任务是包路径，依据javaPackage生成
     */
    private String packagePath;
    private String javaFilePath;
    private String importPackage = "";

    private String javaName;
    private String javaPackage;
    private String content = "";


    public BIGenerateBasicJavaFile(String packagePath, String javaName, String javaPackage) {
        this.packagePath = packagePath;
        this.javaName = javaName;
        this.javaPackage = javaPackage;
        this.javaFilePath = packagePath + File.separator + javaPackage.replace(".", File.separator);
    }

    public void setImportPackage(String importPackage) {
        this.importPackage = importPackage;
    }

    public void writeJavaFile() {
        String fileContent = generateJavaFile();
        FileOperation operation = new FileOperation();
        operation.writerFile(fileContent, javaFilePath + File.separator + javaName + ".java");
    }

    private String generateJavaFile() {
        StringBuffer sb = new StringBuffer();
        sb.append("package ").append(javaPackage).append(";\r\n").append(importPackage).append("\r\n").append("" +
                "/**\r\n" +
                "* This code is generated by tool,Please don't edit it unless you sure \r\n" +
                "* what you are doing very much.\r\n" +
                "**/\r\n");
        sb.append("public class ").append(javaName).append("{\r\n").append(content).append("\r\n}");
        return sb.toString();
    }

    public void addStaticMethod(String name, String body) {
        StringBuffer sb = new StringBuffer(content);
        sb.append("public static void ").append(name).append("()").append("{").append(body).append("}");
        content = sb.toString();
    }
}