package com.fr.bi;

import com.fr.bi.common.factory.IFactoryService;
import com.fr.bi.common.factory.BIMateFactory;
import com.fr.bi.common.factory.BIFactoryKeyDuplicateException;
import com.fr.bi.stable.utils.code.BILogger;

/**
 * This code is generated by tool,Please don't edit it unless you sure
 * what you are doing very much.
 **/
public class FbiConfFactory {
    public static void registerModuleBeans() {
        try {
            IFactoryService xmlFactory = ((IFactoryService) BIMateFactory.getInstance().getObject(IFactoryService.CONF_XML, new Object[]{}));

            try {
                xmlFactory.registerClass("com.fr.bi.conf.manager.userInfo.manager.LoginUserInfoManager", com.fr.bi.conf.manager.userInfo.manager.LoginUserInfoManager.class);
            } catch (BIFactoryKeyDuplicateException ignore) {
                BILogger.getLogger().error(ignore.getMessage(), ignore);
            }
        } catch (Exception ignoreE) {
            BILogger.getLogger().error(ignoreE.getMessage(), ignoreE);
        }
    }
}
