//放置用户不可配置的常量
//dashboard toolbar left button group
BICst.DASHBOARD_TOOLBAR_SAVEAS = 1;
BICst.DASHBOARD_TOOLBAR_UNDO = 2;
BICst.DASHBOARD_TOOLBAR_REDO = 3;


//字段选择，业务包/复用
BICst.DETAIL_PACKAGES_FIELD = 1;
BICst.DETAIL_DIMENSION_REUSE = 2;

//类型&数据/样式tab
BICst.DETAIL_TAB_TYPE_DATA = 1;
BICst.DETAIL_TAB_STYLE = 2;

/*
 *组件、控件的各个操作
 */
BICst.DASHBOARD_WIDGET_DELETE = -1;   //删除
BICst.DASHBOARD_WIDGET_EXPAND = 1;   //详细设置
BICst.DASHBOARD_WIDGET_SHRINK = 2;   //回到组件
BICst.DASHBOARD_WIDGET_LINKAGE = 3;    //联动
BICst.DASHBOARD_DETAIL_WIDGET_DRILL = 13; //钻取到明细表
BICst.DASHBOARD_WIDGET_EXCEL = 4;    //组件、明细表的导出为excel
BICst.DASHBOARD_CONTROL_RANG_ASC = 5;
BICst.DASHBOARD_CONTROL_RANG_DESC = 6;    //文本，下拉树的升序，降序
BICst.DASHBOARD_TIEM_CONTROL_DETAIL = 8;

BICst.DASHBOARD_TIEM_CONTROL_YEAR = 9;
BICst.DASHBOARD_TIEM_CONTROL_SEASON = 10;
BICst.DASHBOARD_TIEM_CONTROL_MONTH = 11;
BICst.DASHBOARD_TIEM_CONTROL_YMD = 13; //日期控件的具体选择、年份、季度、月份
BICst.DASHBOARD_WIDGET_EASY_SETTING = 12;  //快捷设置
BICst.DASHBOARD_CONTROL_CLEAR = 14;       //控件的清空按钮

BICst.DASHBOARD_WIDGET_COPY = 15;  //复制控件
BICst.DASHBOARD_TABLE_FREEZE = 16;

BICst.DASHBOARD_WIDGET_SHOW_NAME = 17;      //显示标题
BICst.DASHBOARD_WIDGET_RENAME = 18;         //重命名
BICst.DASHBOARD_WIDGET_NAME_POS = 19;           //标题位置
BICst.DASHBOARD_WIDGET_NAME_POS_LEFT = 20;      //标题位置居左
BICst.DASHBOARD_WIDGET_NAME_POS_CENTER = 21;     //标题位置居右
BICst.DASHBOARD_WIDGET_FILTER = 22;         //查看过滤条件

BICst.DASHBOARD_WIDGET_SWITCH_CHART = 23;   //查看状态下的切换图表

//维度下拉选项
BICst.DIMENSION_STRING_COMBO = {
    ASCEND: 100,
    DESCEND: 101,
    SORT_BY_CUSTOM: 102,
    GROUP_BY_VALUE: 103,
    GROUP_BY_CUSTOM: 104,
    FILTER: 105,
    DT_RELATION: 106,
    COPY: 107,
    DELETE: 108,
    INFO: 109,
    ADDRESS: 110,
    LNG_LAT: 111,
    LNG: 112,
    LAT: 113
};

BICst.DIMENSION_NUMBER_COMBO = {
    ASCEND: 200,
    DESCEND: 201,
    NOT_SORT: 202,
    SORT_BY_CUSTOM: 203,
    GROUP_BY_VALUE: 204,
    GROUP_SETTING: 205,
    FILTER: 206,
    DT_RELATION: 207,
    COPY: 208,
    DELETE: 209,
    INFO: 210,
    CORDON: 211,
    ADDRESS: 212,
    LNG_LAT: 213,
    LNG: 214,
    LAT: 215
};

BICst.DIMENSION_DATE_COMBO = {
    DATE: 300,
    YEAR: 301,
    QUARTER: 302,
    MONTH: 303,
    WEEK: 304,
    ASCEND: 305,
    DESCEND: 306,
    FILTER: 307,
    DT_RELATION: 308,
    COPY: 309,
    DELETE: 310,
    INFO: 31,
    ADDRESS: 32,
    LNG_LAT: 33,
    LNG: 34,
    LAT: 35
};

//指标下拉选项
BICst.TARGET_COMBO = {
    SUMMERY_TYPE: 400,
    CHART_TYPE: 401,
    STYLE_SETTING: 402,
    FILTER: 403,
    DISPLAY: 404,
    HIDDEN: 405,
    COPY: 406,
    DELETE: 407,
    INFO: 408,
    DEPEND_TYPE: 409,
    CORDON: 410
};

//明细表维度下拉选项
BICst.DETAIL_STRING_COMBO = {
    FILTER: 500,
    HYPERLINK: 501,
    DELETE: 502,
    INFO: 503
};

BICst.DETAIL_NUMBER_COMBO = {
    FORM_SETTING: 600,
    FILTER: 601,
    HYPERLINK: 602,
    DELETE: 603,
    INFO: 604
};

BICst.DETAIL_DATE_COMBO = {
    YMD: 700,
    YMD_HMS: 701,
    YEAR: 702,
    SEASON: 703,
    MONTH: 704,
    WEEK: 705,
    FILTER: 706,
    HYPERLINK: 707,
    DELETE: 708,
    INFO: 709
};

BICst.DETAIL_FORMULA_COMBO = {
    FORM_SETTING: 800,
    UPDATE_FORMULA: 801,
    HYPERLINK: 802,
    DISPLAY: 803,
    HIDDEN: 804,
    RENAME: 805,
    DELETE: 806,
    INFO: 807
};

BICst.CALCULATE_TARGET_COMBO = {
    FORM_SETTING: 900,
    UPDATE_TARGET: 901,
    DISPLAY: 902,
    HIDDEN: 903,
    RENAME: 904,
    COPY: 905,
    DELETE: 906,
    INFO: 907
};


BICst.CONTROL_COMBO = {
    DELETE: 505,
    INFO: 506,
    RENAME: 507
};

//分组统计下拉选项
BICst.STATISTICS_GROUP_DATE_COMBO = {
    DATE: 900,
    YEAR: 901,
    QUARTER: 902,
    MONTH: 903,
    WEEK: 904,
    DELETE: 905,
    No_Repeat_Count: 899,
    DISPLAY: 898,
    HIDDEN: 897,
    RENAME: 896,
    RECORD_COUNT: 895
};

BICst.STATISTICS_GROUP_NUMBER_COMBO = {
    SUM: 906,
    AVG: 907,
    MAX: 908,
    MIN: 909,
    No_Repeat_Count: 910,
    DELETE: 911,
    GROUP_SETTING: 912,
    GROUP_BY_VALUE: 913,
    DISPLAY: 904,
    HIDDEN: 905,
    RENAME: 903,
    RECORD_COUNT: 902
};

BICst.STATISTICS_GROUP_STRING_COMBO = {
    GROUP_BY_VALUE: 913,
    GROUP_BY_CUSTOM: 914,
    No_Repeat_Count: 915,
    DELETE: 916,
    APPEND: 917,
    DISPLAY: 912,
    HIDDEN: 911,
    RENAME: 910,
    RECORD_COUNT: 909
};

BICst.FILTER_TYPE_FORMULA = 10002;
BICst.FILTER_TYPE_FORMULA_EMPTY = -10002;

BICst.TARGET_FILTER_TYPE_NONE = -1;         //含有combo，类型待确定
BICst.DIMENSION_FILTER_TYPE_NONE = -2;
BICst.TARGET_FILTER_CONTAINER_EMPTY = -3;   //empty的
BICst.DIMENSION_FILTER_CONTAINER_EMPTY = -4;   //empty的
BICst.FILTER_CONTAINER_EMPTY = -100;

BICst.FILTER_OPERATION_FORMULA = 1;
BICst.FILTER_OPERATION_CONDITION = 2;
BICst.FILTER_OPERATION_CONDITION_AND = 3;
BICst.FILTER_OPERATION_CONDITION_OR = 4;
BICst.FILTER_OPERATION_FORMULA_AND = 5;
BICst.FILTER_OPERATION_FORMULA_OR = 6;

BICst.NUMBER_INTERVAL_CUSTOM_GROUP_CUSTOM = 5;
BICst.NUMBER_INTERVAL_CUSTOM_GROUP_VALUE = 4;
BICst.NUMBER_INTERVAL_CUSTOM_GROUP_AUTO = 3;

BICst.FILTER_PANE_CLICK_REMOVE = -1;
BICst.FILTER_PANE_CLICK_EXPANDER = 1;
BICst.FILTER_PANE_CLICK_ITEM = 2;

//etl pane card names (empty tip, only one tip, pane)
BICst.CONF_ETL_DATA_SET_EMPTY_TIP = "data_set_empty_tip";
BICst.CONF_ETL_DATA_SET_ONLY_ONE_TIP = "data_set_only_one_tip";
BICst.CONF_ETL_DATA_SET_PANE = "data_set_pane";
BICst.CONF_ETL_SET_EMPTY_TIP = "etl_empty_tip";
BICst.CONF_ETL_SET_PANE = "etl_set_pane";


BICst.ADD_NEW_TABLE = {
    DATABASE_OR_PACKAGE: 1,
    ETL: 2,
    SQL: 3,
    EXCEL: 4,
    NONE: -1
};

BICst.TABLES_VIEW = {
    TILE: 1,
    RELATION: 2
};

//定义组件的三个状态，查看状态的dashboard、编辑状态的dashboard、详细设置
BICst.WIDGET_STATUS = {
    SHOW: 1,
    EDIT: 2,
    DETAIL: 3
};