package com.fr.bi;

import com.fr.bi.stable.utils.code.BILogger;

/**
 * This code is generated by tool,Please don't edit it unless you sure
 * what you are doing very much.
 **/
public class SystemFactoryRegister {
    public static void systemRegister() {
        try {

        } catch (Exception ignore) {
            BILogger.getLogger().error(ignore.getMessage(), ignore);
        }
    }
}