package com.fr.bi;

import com.finebi.cube.common.log.BILoggerFactory;

/**
 * This code is generated by tool,Please don't edit it unless you sure
 * what you are doing very much.
 **/
public class SystemFactoryRegister {
    public static void systemRegister() {
        try {

        } catch (Exception ignore) {
            BILoggerFactory.getLogger().error(ignore.getMessage(), ignore);
        }
    }
}