package com.fr.bi;
import com.fr.bi.common.factory.IFactoryService;
import com.fr.bi.common.factory.BIMateFactory;
import com.fr.bi.common.factory.BIFactoryKeyDuplicateException;
import com.finebi.cube.common.log.BILoggerFactory;
/**
* This code is generated by tool,Please don't edit it unless you sure 
* what you are doing very much.
**/
public class FbiAnalysisEtlFactory{
public static void registerModuleBeans(){
	try{
		IFactoryService xmlFactory =((IFactoryService) BIMateFactory.getInstance().getObject( IFactoryService.CONF_XML , new Object[]{}));
		try{
			xmlFactory.registerClass("com.fr.bi.etl.analysis.manager.SingleUserAnalysisBusiPackManager",com.fr.bi.etl.analysis.manager.SingleUserAnalysisBusiPackManager.class);}
		catch(BIFactoryKeyDuplicateException ignore){
			 BILoggerFactory.getLogger().error(ignore.getMessage(),ignore);
			}}
		catch(Exception ignoreE){
		 BILoggerFactory.getLogger().error(ignoreE.getMessage(),ignoreE);
		}}
}